In [44]:
import numpy as np

In [45]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [46]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
arr2.ndim

2

In [48]:
arr2.shape

(2, 4)

In [49]:
arr1.dtype

dtype('float64')

In [50]:
arr2.dtype

dtype('int64')

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
np.empty((2,3,2))

array([[[5.44689690e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [2.14321575e-312, 5.15248504e-062]],

       [[6.57910926e-038, 6.89607558e-042],
        [1.27856020e+161, 1.20075656e-075],
        [2.37776545e+184, 1.39872067e-076]]])

In [54]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
arr1.dtype

dtype('float64')

In [56]:
arr2.dtype

dtype('int32')

In [57]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [58]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [59]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [60]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [61]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [62]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [63]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [64]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [66]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [67]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr[5]

5

In [69]:
arr[5:8]

array([5, 6, 7])

In [70]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [71]:
arr_slice = arr[5:8]

In [72]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [73]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])